-- v125 Platform Control migration
-- Runtime schema creation is also included in public/index.php, so this file is optional.
ALTER TABLE companies ADD COLUMN account_status VARCHAR(20) NOT NULL DEFAULT 'active';
ALTER TABLE companies ADD COLUMN plan_name VARCHAR(80) NOT NULL DEFAULT 'Trial';
ALTER TABLE companies ADD COLUMN subscription_expires_at DATETIME NULL;
CREATE TABLE IF NOT EXISTS platform_login_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,user_id INT UNSIGNED NOT NULL,company_id INT UNSIGNED NOT NULL,ip_address VARCHAR(64) NULL,user_agent VARCHAR(500) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_ple_company(company_id,created_at),KEY idx_ple_user(user_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS platform_sessions (session_id VARCHAR(191) NOT NULL,user_id INT UNSIGNED NOT NULL,company_id INT UNSIGNED NOT NULL,last_seen_at DATETIME NOT NULL,created_at DATETIME NOT NULL,ip_address VARCHAR(64) NULL,user_agent VARCHAR(500) NULL,PRIMARY KEY(session_id),KEY idx_ps_company(company_id,last_seen_at),KEY idx_ps_last_seen(last_seen_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS platform_announcements (id INT UNSIGNED NOT NULL AUTO_INCREMENT,title VARCHAR(191) NOT NULL,body TEXT NOT NULL,type VARCHAR(20) NOT NULL DEFAULT 'notice',target_type VARCHAR(20) NOT NULL DEFAULT 'all',target_company_id INT UNSIGNED NULL,priority INT NOT NULL DEFAULT 0,is_active TINYINT(1) NOT NULL DEFAULT 1,starts_at DATETIME NOT NULL,ends_at DATETIME NULL,created_by INT UNSIGNED NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_pa_active(is_active,starts_at,ends_at),KEY idx_pa_company(target_company_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS platform_announcement_reads (announcement_id INT UNSIGNED NOT NULL,user_id INT UNSIGNED NOT NULL,read_at DATETIME NOT NULL,PRIMARY KEY(announcement_id,user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS support_tickets (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,company_id INT UNSIGNED NOT NULL,user_id INT UNSIGNED NULL,subject VARCHAR(191) NOT NULL,category VARCHAR(40) NOT NULL DEFAULT 'bug',message TEXT NOT NULL,priority VARCHAR(20) NOT NULL DEFAULT 'normal',status VARCHAR(20) NOT NULL DEFAULT 'open',admin_reply TEXT NULL,admin_replied_by INT UNSIGNED NULL,admin_replied_at DATETIME NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),KEY idx_st_company(company_id,created_at),KEY idx_st_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
